apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "final-q-native"
  description: "q test native"
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/quarkus
  consumesApis: 
    - quarkus-final